### ISSUE TITLE
dialog.tlk

### ISSUE THREAD

**Issue by proletariado** [micah-yeager/kotor-ii-switch-modding#5]
[SWITCH TSLRCM dialog FIXED.zip](https://github.com/DrSnuggly/kotor-ii-switch-modding/files/12027719/SWITCH.TSLRCM.dialog.FIXED.zip)

Here's the Switch dialog.tlk with the TSLRCM changes (it preserves Switch interface elements like button prompts etc).

You could append a copy and replace operation to the very end of your script.

**Comment by maia-yeager** [comment]
Hey, much appreciated!! I’ll take a look in the next day or two.

Just double-checking instead of assuming — are you ok if I incorporate your work into this project? I can add you as a contributor.

**Comment by proletariado** [comment]
Of course, I want people to make use of it. You have my blessing :)

I completed a full playthrough with it and ran into no bugs.

**Comment by maia-yeager** [comment]
File has been uploaded as part of the latest release!

However, I've added it as an asset for the newest release (on GitHub and DeadlyStream), with a mention under **Platform-specific known issues and fixes**, rather than integrating it directly in the script. I did it this way since some users might not being using TSLRCM.

What would your thoughts be on creating a TSLPatcher-based mod? I figure that way your fixes can be integrated into any mod on the Switch platform. If that's not something you're comfortable doing, I could try to make it myself if you're able to provide me a comprehensive list of changes you made.

**Comment by proletariado** [comment]
I wish I had kept the scripts I wrote to compare and merge the differences, but alas I did not. This all started for personal use, I didn't think anyone else was going to go this far! The logic used was thus:

I compared the stock switch dialog.tlk with the TSLRCM dialog.tlk. If there was an entry in both (same id), I kept the contents of the switch version. If either had an entry with a unique id, it was preserved and added to the final output.

I hope that helps if you decide to bother with a patcher.

**Comment by maia-yeager** [comment]
All good. I'll keep that in mind and maybe make another project with the TSLPatcher idea. Regardless, appreciate you taking the time to create this!

I'll go ahead and close this one out, but don't hesitate to let me know if you have any other ideas.
